
def extract_emotion_from_text(generated_text):
    """
    Extracts the emotion label from the generated text.

    Args:
        generated_text: Text generated by the model.

    Returns:
        predicted_emotion: Integer or string representing the predicted emotion.
    """
    # Example implementation (you should adjust based on your text format):
    emotion_mapping = {
        "happy": 0,
        "sad": 1,
        "angry": 2,
        "neutral": 3,
        # Add your dataset-specific mappings
    }
    for emotion, label in emotion_mapping.items():
        if emotion in generated_text.lower():
            return label
    return None  # Return None if no emotion is found